/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#87c7fd",
        "secondary-container": "#ffc5a8",
        "on-secondary-fixed": "#5a2400",
        "error": "#b31b25",
        "surface-container-high": "#a2f0ef",
        "outline-variant": "#7db7b7",
        "secondary-dim": "#813c0e",
        "primary": "#00675e",
        "on-primary": "#c0fff5",
        "tertiary-fixed-dim": "#79baee",
        "error-dim": "#9f0519",
        "tertiary": "#0a6190",
        "on-surface": "#003535",
        "on-secondary-container": "#773405",
        "inverse-on-surface": "#6da7a6",
        "secondary-fixed-dim": "#ffb289",
        "inverse-primary": "#6cffed",
        "surface-tint": "#00675e",
        "on-tertiary-fixed-variant": "#004970",
        "primary-fixed-dim": "#4ce5d4",
        "on-secondary": "#fff0e9",
        "on-background": "#003535",
        "inverse-surface": "#001111",
        "tertiary-dim": "#005480",
        "tertiary-fixed": "#87c7fd",
        "on-error-container": "#570008",
        "outline": "#468080",
        "on-primary-container": "#005951",
        "surface": "#d2fffe",
        "primary-container": "#5ef3e2",
        "on-tertiary": "#eaf4ff",
        "background": "#d2fffe",
        "surface-container": "#adf5f4",
        "on-secondary-fixed-variant": "#833d0f",
        "on-error": "#ffefee",
        "error-container": "#fb5151",
        "on-primary-fixed-variant": "#00635a",
        "on-tertiary-container": "#004063",
        "on-primary-fixed": "#00443e",
        "surface-variant": "#96ebeb",
        "surface-dim": "#87e4e3",
        "on-surface-variant": "#286464",
        "secondary-fixed": "#ffc5a8",
        "surface-container-highest": "#96ebeb",
        "surface-bright": "#d2fffe",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002a43",
        "primary-dim": "#005a52",
        "surface-container-low": "#bafdfc",
        "secondary": "#904719",
        "primary-fixed": "#5ef3e2"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
