/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fffaf9",
        "surface-container-low": "#f4f9f7",
        "on-secondary-container": "#334a44",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#98a6a1",
        "inverse-surface": "#0f1211",
        "primary": "#ff7f78",
        "primary-mint": "#4fd1c5",
        "primary-mint-dark": "#38b2ac",
        "error-container": "#fa746f",
        "on-tertiary-fixed-variant": "#714e5b",
        "surface-container-high": "#e8f7f2",
        "surface-dim": "#d4e0db",
        "secondary": "#577a72",
        "on-secondary-fixed": "#344d47",
        "tertiary-container": "#fbd1e7",
        "tertiary": "#8c4d68",
        "primary-fixed-dim": "#ffb4ab",
        "surface-tint": "#ff7f78",
        "secondary-container": "#e7fbf5",
        "on-tertiary-container": "#6b334a",
        "secondary-dim": "#42665e",
        "primary-dim": "#e5625d",
        "on-error-container": "#6e0a12",
        "on-error": "#fff7f6",
        "tertiary-fixed-dim": "#f7bed9",
        "on-background": "#2e3432",
        "error-dim": "#67040d",
        "on-tertiary": "#ffffff",
        "surface-variant": "#dfece8",
        "on-surface-variant": "#59615e",
        "on-secondary-fixed-variant": "#4d605a",
        "on-tertiary-fixed": "#533241",
        "error": "#a83836",
        "on-primary-fixed": "#4d100d",
        "tertiary-dim": "#824b64",
        "surface": "#f9fffb",
        "on-surface": "#2e3432",
        "secondary-fixed-dim": "#d4e7e1",
        "surface-container-highest": "#dfece8",
        "on-primary-container": "#4d100d",
        "outline-variant": "#aab4b0",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e7fbf5",
        "on-primary-fixed-variant": "#6a1b18",
        "tertiary-fixed": "#fbd1e7",
        "background": "#f9fffb",
        "inverse-primary": "#ffb4ab",
        "primary-fixed": "#ffdad6",
        "surface-container": "#f0f9f5",
        "primary-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "outline": "#747c78"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Work Sans"],
        "label": ["Work Sans"]
      },
      borderRadius: { "DEFAULT": "2px", "md": "3px", "lg": "4px", "xl": "6px", "2xl": "8px", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
